apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-db
  template:
    metadata:
      labels:
        app: category-db
    spec:
      containers:
      - name: category-db
        image: mongo:7-jammy
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: category-db-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: category-db-secret
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: category-db-secret
              key: database
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: category-db-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: category-db-config
data:
  MONGO_USERNAME: "ydh2244"
  MONGO_PASSWORD: "1127star@"
  MONGO_DATABASE: "categorydb"
