apiVersion: v1
kind: Service
metadata:
  name: category-db-service
spec:
  selector:
    app: category-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP # 클러스터 내부에서만 접근 가능
