apiVersion: v1
kind: Service
metadata:
  name: category-db
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: category-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017