# Post Service 설정 파일
# deployment.yaml의 환경 변수를 통해 실제 값이 오버라이드됩니다.

server:
  port: 8084

spring:
  application:
    name: post-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mariadb://localhost:3307/signite}
    username: ${SPRING_R2DBC_USERNAME:user}
    password: ${SPRING_R2DBC_PASSWORD:password}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
  webflux:
    cors:
      enabled: true

# 로깅 설정
logging:
  level:
    com.signite.postservice: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.data.elasticsearch: DEBUG
