apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: post-service
        image: signite/post-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
          - name: SPRING_R2DBC_URL
            value: "r2dbc:mariadb://post-db:3306/postdb"
          - name: SPRING_R2DBC_USERNAME
            valueFrom:
              secretKeyRef:
                name: post-db-secret
                key: MYSQL_USER
          - name: SPRING_R2DBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: post-db-secret
                key: MYSQL_PASSWORD
          - name: SPRING_ELASTICSEARCH_URIS
            value: "http://post-search:9200"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
