apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: post-service
        image: signite/post-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          # Spring Boot 프로퍼티 형식에 맞는 환경 변수 이름을 사용합니다.
          - name: SPRING_DATA_MONGODB_URI
            value: "mongodb://root:password@post-db-service:27017/postdb?authSource=admin"
          - name: SPRING_ELASTICSEARCH_URIS
            value: "http://post-search-service:9200"
          - name: grpc.client.category-service.address
            value: "static://category-service-service:9090"
          - name: grpc.client.category-service.negotiation-type
            value: "plaintext"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
