apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  selector:
    app: post-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8084
  type: ClusterIP
