apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-deployment
  labels:
    app: comment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: comment-service
        image: signite/comment-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
          - name: APP_DATABASE__URI
            value: "mongodb://root:password@comment-db-service:27017"
          - name: DATABASE_NAME
            value: "commentdb"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
