apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-deployment
  labels:
    app: comment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: comment-service
        image: nginxdemos/hello:0.3-plain-text
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: APP_DATABASE__URI
            value: "mongodb://root:password@comment-db-service:27017"
          - name: DATABASE_NAME
            value: "commentdb"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
