apiVersion: v1
kind: Service
metadata:
  name: comment-service-service
  labels:
    app: comment-service
spec:
  selector:
    app: comment-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
