apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: default
spec:
  replicas: 2  # 고가용성을 위한 2개 레플리카
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket
        image: signight/websocket:latest
        ports:
        - containerPort: 8080
          name: websocket
          protocol: TCP
        - containerPort: 3001
          name: health
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "rust_websocket_server=info,debug"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "8080"
        - name: HTTP_PORT
          value: "3001"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: MONGODB_URL
          value: "mongodb://mongo-service:27017"
        - name: MONGODB_DB_NAME
          value: "signight_websocket"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: JWT_ISSUER
          value: "https://auth.signite.com"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:5174,https://signight.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: default
spec:
  selector:
    app: websocket-server
  ports:
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: health
    port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
  sessionAffinity: ClientIP  # Sticky sessions for WebSocket

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: websocket-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websocket-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80