apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
        version: v1
    spec:
      containers:
      - name: websocket-server
        image: signite-websocket:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: websocket
          protocol: TCP
        - containerPort: 3001
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: websocket-config
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: websocket-secret
              key: MONGODB_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: websocket-secret
              key: JWT_SECRET
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: websocket-secret
              key: REDIS_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  selector:
    app: websocket-server
  ports:
  - name: websocket
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service-nodeport
spec:
  selector:
    app: websocket-server
  ports:
  - name: websocket
    port: 8080
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
  - name: http
    port: 3001
    targetPort: 3001
    nodePort: 30082
    protocol: TCP
  type: NodePort 