apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: signight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: server
        image: signight-backend:v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_R2DBC_URL
          value: "r2dbc:mysql://signight-mariadb:3306/signight"
        - name: SPRING_R2DBC_USERNAME
          value: "signight"
        - name: SPRING_R2DBC_PASSWORD
          value: "signight123"
        - name: SPRING_R2DBC_HOST
          value: "signight-mariadb"
        - name: SPRING_R2DBC_PORT
          value: "3306"
        - name: SPRING_R2DBC_DATABASE
          value: "signight"
        - name: SPRING_DATA_REDIS_HOST
          value: "signight-redis"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: "signight-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          value: "C877E4A955FBDB2257CCB64154D1D59F1546ED967473C128E477DC9467"
        - name: MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED
          value: "false"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        - name: NATS_SERVER_URL
          value: "nats://nats-client:4222"
        - name: SERVER_PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi" 