apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: auth-service-sa
      containers:
      - name: auth-service
        image: signite/auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: category-db-secret
              key: uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_SECRET
        - name: REDIS_HOST
          value: redis-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 5