apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: default
  labels:
    app: auth-service
automountServiceAccountToken: true

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  jwt-secret: "c2lnbmlnaHQtand0LXNlY3JldC0yMDI1"  # signite-jwt-secret-2025