apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: auth-service
  type: ClusterIP