apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  labels:
    app: auth-service
spec:
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  selector:
    app: auth-service
  type: ClusterIP