apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: websocket-mongo
spec:
  serviceName: "websocket-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: websocket-mongo
  template:
    metadata:
      labels:
        app: websocket-mongo
    spec:
      containers:
      - name: websocket-mongo
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "ydh2244"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "1127star"
        - name: MONGO_INITDB_DATABASE
          value: "signight_websocket"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        - name: mongo-config-volume
          mountPath: /etc/mongod.conf
          subPath: mongo.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: websocket-mongo-pvc
      - name: mongo-config-volume
        configMap:
          name: websocket-mongo-config

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: websocket-mongo 