spring:
  r2dbc:
    url: r2dbc:postgresql://category-db-service:5432/categorydb
    username: user
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql