apiVersion: apps/v1
kind: Deployment
metadata:
  name: nested-api-deployment
  labels:
    app: nested-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nested-api
  template:
    metadata:
      labels:
        app: nested-api
    spec:
      containers:
      - name: nested-api
        image: httpd:2.4-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nested-api-content
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: nested-api-content
        configMap:
          name: nested-api-content
---
apiVersion: v1
kind: Service
metadata:
  name: nested-api-service
  labels:
    app: nested-api
spec:
  selector:
    app: nested-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nested-api-content
data:
  categories-1-posts.json: |
    {
      "category_id": 1,
      "category_name": "기술",
      "posts": [
        {
          "id": 1,
          "title": "첫 번째 포스트",
          "content": "안녕하세요! 첫 포스트입니다.",
          "category_id": 1,
          "created_at": "2025-07-31T16:00:00Z"
        },
        {
          "id": 3,
          "title": "기술 블로그",
          "content": "Kubernetes 배포 경험기",
          "category_id": 1,
          "created_at": "2025-07-31T14:00:00Z"
        }
      ],
      "total": 2,
      "status": "success"
    }
  categories-2-posts.json: |
    {
      "category_id": 2,
      "category_name": "일상",
      "posts": [],
      "total": 0,
      "status": "success"
    }
  categories-3-posts.json: |
    {
      "category_id": 3,
      "category_name": "여행",
      "posts": [
        {
          "id": 2,
          "title": "여행 후기",
          "content": "제주도 여행 다녀왔어요!",
          "category_id": 3,
          "created_at": "2025-07-31T15:00:00Z"
        }
      ],
      "total": 1,
      "status": "success"
    }
  posts-1-comments.json: |
    {
      "post_id": 1,
      "post_title": "첫 번째 포스트",
      "comments": [
        {
          "id": 1,
          "post_id": 1,
          "author": "김철수",
          "content": "좋은 글이네요!",
          "created_at": "2025-07-31T16:10:00Z"
        },
        {
          "id": 2,
          "post_id": 1,
          "author": "이영희",
          "content": "동감합니다.",
          "created_at": "2025-07-31T16:15:00Z"
        }
      ],
      "total": 2,
      "status": "success"
    }
  posts-2-comments.json: |
    {
      "post_id": 2,
      "post_title": "여행 후기",
      "comments": [
        {
          "id": 3,
          "post_id": 2,
          "author": "박민수",
          "content": "저도 제주도 가고싶어요",
          "created_at": "2025-07-31T16:20:00Z"
        }
      ],
      "total": 1,
      "status": "success"
    }
  posts-3-comments.json: |
    {
      "post_id": 3,
      "post_title": "기술 블로그",
      "comments": [],
      "total": 0,
      "status": "success"
    }
  categories-1-posts-1-comments.json: |
    {
      "category_id": 1,
      "category_name": "기술",
      "post_id": 1,
      "post_title": "첫 번째 포스트",
      "comments": [
        {
          "id": 1,
          "post_id": 1,
          "author": "김철수",
          "content": "좋은 글이네요!",
          "created_at": "2025-07-31T16:10:00Z"
        },
        {
          "id": 2,
          "post_id": 1,
          "author": "이영희",
          "content": "동감합니다.",
          "created_at": "2025-07-31T16:15:00Z"
        }
      ],
      "total": 2,
      "status": "success"
    }