version: '3.8'

services:
  websocket:
    build: .
    container_name: signight-websocket
    restart: always  # 자동 재시작 설정
    ports:
      - "8080:8080"  # WebSocket 포트
      - "3001:3001"  # Health check 포트
    environment:
      - RUST_LOG=rust_websocket_server=info,debug
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - HTTP_PORT=3001
      - REDIS_URL=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DB_NAME=signight_websocket
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key}
      - JWT_ISSUER=https://auth.signite.com
      - ALLOWED_ORIGINS=http://localhost:5174,https://signight.com
    depends_on:
      - redis
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  redis:
    image: redis:7-alpine
    container_name: signight-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6
    container_name: signight-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=signight_websocket
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  mongo_data: